class YouTubeCaptionTrack {
  YouTubeCaptionTrack({
    required this.id,
    required this.language,
    required this.name,
    required this.isAutoGenerated,
  });

  final String id;
  final String language;
  final String name;
  final bool isAutoGenerated;

  factory YouTubeCaptionTrack.fromCaptionItem(Map<String, dynamic> item) {
    final snippet = (item['snippet'] as Map<String, dynamic>?) ??
        const <String, dynamic>{};
    final trackKind = (snippet['trackKind'] as String?) ?? '';

    return YouTubeCaptionTrack(
      id: (item['id'] as String?) ?? '',
      language: (snippet['language'] as String?) ?? 'und',
      name: (snippet['name'] as String?) ?? '',
      isAutoGenerated: trackKind.toLowerCase() == 'asr',
    );
  }
}
